#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh &
feh --bg-scale $HOME/Pictures/wallpapers/primary.jpg
nm-applet &
#bspc monitor -d
bspc monitor LVDS-1 -d   
bspc monitor VGA-1 -d  

bspc config border_width         2
bspc config window_gap           0
bspc config focus_follows_pointer true
bspc config pointer_modifier	mod1

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
